[GLOBAL]
pants_version = "2.15.0.dev4"
backend_packages.add = [
  "pants.backend.experimental.go",
  #"pants.backend.experimental.go.debug_goals",
]

[source]
root_patterns = ["/"]

[golang]
minimum_expected_version = "1.17"
cgo_enabled = true

[anonymous-telemetry]
enabled = false
