[GLOBAL]
pants_version = "2.16.0.dev0"
backend_packages.add = [
  "pants.backend.experimental.go",
  "pants.backend.experimental.go.debug_goals",
  "pants.backend.shell",
]

[source]
root_patterns = ["/"]

[golang]
minimum_expected_version = "1.17"
cgo_enabled = true

[anonymous-telemetry]
enabled = false
